/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.maps.android.compose.multiplatform.demo

import androidx.compose.ui.window.ComposeUIViewController
import platform.Foundation.NSUserDefaults
import platform.UIKit.UIViewController

/**
 * The demo app as a view controller, for the iOS app's window.
 *
 * Launching the app with `-demo <index>` opens that demo directly, for example
 * `xcrun simctl launch booted com.google.maps.android.compose.iosApp -demo 3`.
 */
public fun MainViewController(): UIViewController = ComposeUIViewController(
    configure = {
        // The demo app's Info.plist is generated by create_project.rb and is not checked by
        // Compose's sanity checks.
        enforceStrictPlistSanityCheck = false
    },
) {
    MultiplatformDemoApp(
        startDemo = NSUserDefaults.standardUserDefaults.stringForKey("demo")?.toIntOrNull(),
    )
}
